spring:
  jpa:
    database: POSTGRESQL
    show-sql:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/ocr_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
